// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupermarketSystem.CashierApp.Local;

#nullable disable

namespace SupermarketSystem.CashierApp.Local.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    partial class LocalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SupermarketSystem.CashierApp.Local.LocalPaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresExternalReference")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("SupermarketSystem.CashierApp.Local.LocalProduct", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailableForSale")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBatchTracked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SupermarketSystem.CashierApp.Local.LocalProductBarcode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BarcodeValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductUnitId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeValue")
                        .IsUnique();

                    b.ToTable("ProductBarcodes");
                });

            modelBuilder.Entity("SupermarketSystem.CashierApp.Local.LocalProductBatch", b =>
                {
                    b.Property<Guid>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantityAvailable")
                        .HasColumnType("TEXT");

                    b.HasKey("BatchId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductBatches");
                });

            modelBuilder.Entity("SupermarketSystem.CashierApp.Local.LocalProductUnit", b =>
                {
                    b.Property<Guid>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConversionFactorToBase")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBaseUnit")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UnitId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductUnits");
                });

            modelBuilder.Entity("SupermarketSystem.CashierApp.Local.PendingSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAttemptAtLocal")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientRequestId")
                        .IsUnique();

                    b.ToTable("PendingSales");
                });

            modelBuilder.Entity("SupermarketSystem.CashierApp.Local.SyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSuccessfulSyncAtLocal")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSyncedCatalogVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncStates");
                });
#pragma warning restore 612, 618
        }
    }
}
